### ISSUE TITLE
Support steps only for some files

### ISSUE THREAD

**Issue by chshersh** [rhyskeepence/trigger#3]
The project is very cool! This is exactly what I was looking for quite a long time. But it doesn't cover all my cases. I would like to be able to specify commands for various types. For example, I have a website that should be regenerated if any of the content files is changed and if any Haskell file changes, it also should be recompiled.

It would be really nice to support something like this!

**Comment by rhyskeepence** [comment]
Thanks for raising this. I don't have your particular use case, so I might have misunderstood you. But I think right now you can do something like this, which will monitor both `*.hs` and `*.content` and run the relevant build command. 

```
- dirs:
    - "src"
  files:
    - "**/*.content"
  tasks: 
    - "./regenerate"
- dirs:
    - "src"
  files:
    - "**/*.hs"
  tasks: 
    - "stack build"
```
What is not supported is a common background task (the exec command). This is something I could look into. 

Also, dependencies between tasks is not supported. You could imagine that a task could have 'dependsOn', which would cause it to trigger if the first task was triggered. But because I don't have a need for such a feature, I have so far decided not to introduce the additional complexity.
